netty:
  port: 9527
  host: 127.0.0.1
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/chat
    username: root
    password: #######
    type: com.zaxxer.hikari.HikariDataSource
mapper:
  scan:
    basePackage: com.chat.server.dao
mybatis:
  configuration:
    map-underscore-to-camel-case: true